Compatible with Magento 2.3, Disable MultiShipping, Fix UI Error
razorpay/razorpay-magento pull request #129
Opened 2019-03-05 08:41 UTC by seherkdc

Edit Line 2, 26, 28 in **composer.json** before commit.
Important: Change **name** to **razorpay/magento**

2019-03-08 09:51 UTC, captn3m0 requested changes

2019-03-08 09:51 UTC, captn3m0 commented on view/frontend/web/template/payment/razorpay-form.html
> +        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAACJgAAALBCAYAAAAeH4lyAAAABGdBTUEAALGPC/xhBQAA/bVJREFUeNrs3Xm0plddJ/rvfk/NScBMkAAyBEwlKYTIqYEAYiFJLuBwWxcnoCAODCHBVvs2Di1Lu263ra3o7W7pmhI
Can we switch this to https://cdn.razorpay.com/logo.png instead?

2019-03-08 09:51 UTC, captn3m0 commented on Controller/Payment/Order.php
> +	$receipt_id = $this->getQuote()->getId();
nit: fix alignment everywhere please

2019-03-08 09:51 UTC, captn3m0 commented on etc/payment.xml
> +            <allow_multiple_address>0</allow_multiple_address>
@ccrims0n Will this be a breaking change?

@seherkdc What is the impact of this?

2019-03-08 10:41 UTC, seherkdc commented on etc/payment.xml
> +            <allow_multiple_address>0</allow_multiple_address>
This disables Razorpay payment option for Multi-shipping. Magento `MultishippingController` does not support redirect URL for payment gateways. Therefore, multi-shipping needs to be disabled in the existing code.

2019-03-08 10:58 UTC, seherkdc commented on view/frontend/web/template/payment/razorpay-form.html
> +        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAACJgAAALBCAYAAAAeH4lyAAAABGdBTUEAALGPC/xhBQAA/bVJREFUeNrs3Xm0plddJ/rvfk/NScBMkAAyBEwlKYTIqYEAYiFJLuBwWxcnoCAODCHBVvs2Di1Lu263ra3o7W7pmhI
Yes. Use commit no. [071d048](https://github.com/kdclabs/razorpay-magento/commit/071d048788b6896b3618aeea935514b8d4e828e0#diff-38c849ad9f5324a915594a45ec6ba7c4)

2019-05-09 06:48 UTC, ccrims0n commented
@seherkdc Can you please resolve the conflicts

2019-05-16 06:07 UTC, seherkdc commented
@ccrims0n This is an old PR. Individual PRs for each issue have already been shared and resolved.

2019-05-16 06:07 UTC, closed without merging