Disable Razorpay on Multi-Shipping Checkout
razorpay/razorpay-magento pull request #132
Opened 2019-03-08 13:47 UTC by seherkdc

Magento ``MultishippingController`` does not support Redirect URL for payment gateways. Therefore, multi-shipping needs to be disabled here
This resolves issue #61

2019-04-16 09:39 UTC, ccrims0n commented
@seherkdc How can we use this without redirect URL?

2019-04-17 13:12 UTC, seherkdc commented
> @seherkdc How can we use this without redirect URL?

@ccrims0n As mentioned in the Issue Resolution Tracker shared with you via email:
A complete code revision (independent branch) has to be made to deal with this issue as the
existing checkout flow will not cater to handling multiple orders or splitting a single order.
Thus a new repo/branch development is required (Checkout has to be done via API | Seamless).

2019-04-23 04:25 UTC, ccrims0n approved these changes

2019-04-23 04:25 UTC, ccrims0n commented on etc/payment.xml
> +            <allow_multiple_address>0</allow_multiple_address>          //Disable Multi-shipping
please remove the comment

2019-04-23 04:25 UTC, ccrims0n requested changes
.

2019-04-23 06:39 UTC, seherkdc commented on etc/payment.xml
> +            <allow_multiple_address>0</allow_multiple_address>          //Disable Multi-shipping
Done. Comment has been removed.

2019-04-23 06:47 UTC, ccrims0n approved these changes

2019-04-29 07:13 UTC, merged