Added checks for user inputs
razorpay/razorpay-magento pull request #32
Opened 2016-12-21 07:11 UTC by mayankamencherla

Added checks to see if razorpay_payment_id and razorpay_signature is defined.

2016-12-21 07:19 UTC, captn3m0 requested changes

2016-12-21 07:19 UTC, captn3m0 commented on app/code/community/Razorpay/Payments/Model/Paymentmethod.php
> +            throw new Exception('Razorpay Payment Id is not defined');
Is this caught anywhere? Would give a 500 otherwise.

Use $error instead?

2016-12-21 07:19 UTC, captn3m0 commented on app/code/community/Razorpay/Payments/Model/Paymentmethod.php
> +            throw new Exception('Razorpay Payment Id is not defined');
Same thing here as well.

Maybe have a single validation function before that validates the entire $response array instead of this?

2017-01-17 13:08 UTC, 73sl4 commented on app/code/community/Razorpay/Payments/Helper/Data.php
> +            $url = Mage::getUrl('checkout/onepage/failure');
Redirect on the basis of the payment status.

If payment status is successful then just redirect to success, it's failed then redirect to failure page.

2017-01-17 15:01 UTC, mayankamencherla commented on app/code/community/Razorpay/Payments/Helper/Data.php
> +            $url = Mage::getUrl('checkout/onepage/failure');
Over here we're checking if the order status is processing. We haven't created the payment yet on checkout yet, we are in the process of creating the checkout form.

2017-08-16 13:37 UTC, ccrims0n commented
Closing as not relevant.

2017-08-16 13:37 UTC, closed without merging